version: '3'
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    environment:
      - NODE_ENV=production
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - proxy-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - proxy
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500